#cloud-config
groups:
  - ubuntu: [root,sys]
  - hashicorp
users:
  - default
  - name: deploy
    gecos: deploy
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys: 
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVLkgbIbcYQElcrSgt2tZDcjxlnGAjUjrM4iseFod9P jordangrilly@gmail.com #Replace by you ssh public key
packages:
  - python3
runcmd:
  -   alias python=python3